
// actions for fetching question types in Menu  Bar
export const FETCH_QUESTIONTYPES_SUCCESS = 'FETCH_QUESTIONTYPES_SUCCESS'
export const FETCH_QUESTIONTYPES = 'FETCH_QUESTIONTYPES'
export const FETCH_QUESTIONTYPES_FAIL = 'FETCH_QUESTIONTYPES_FAIL'

//Action for Sub menu Toggle
export const TOGGLE_SUBMENU_VISIBILITY = 'TOGGLE_SUBMENU_VISIBILITY'


//Actions for Adding/ POST speaking question
export const POST_SPEAKING = 'POST_SPEAKING'
export const POST_SPEAKING_SUCCESS = 'POST_SPEAKING_SUCCESS'
export const POST_SPEAKING_FAIL = 'POST_SPEAKING_FAIL'
